Fix Übsetzung marital-status “U”
hl7germany/basisprofil-de-r4 pull request #281
Opened 2021-04-27 10:55 UTC by alexzautke

Fixes #241

2021-05-11 15:53 UTC, simoneOnFhir reviewed
ledig steht für:

eine noch nie verheiratete Person, siehe Familienstand
(https://de.wikipedia.org/wiki/Ledig)

Ist das nicht eher "never married"...?

2021-05-16 13:40 UTC, alexzautke commented
Soweit ich das verstehe gibt es in Deutschland keine äquivalentes Mapping dazu. Siehe https://de.wikipedia.org/wiki/Familienstand#cite_note-4 für die erlaubten Werte. Wenn man sich durch ein paar Definition von "unmarried" durchliest wäre das sowas wie eine Lebenspartnerschaft, nur das diese nicht offiziell eingetragen ist.

2021-05-16 13:44 UTC, alexzautke commented
Würde damit beides somit unter das Konzept ledig fallen?

2021-05-19 08:02 UTC, simoneOnFhir commented
Ich verstehe "unmarried" wörtlich als "aktuell gerade nicht verheiratet" ohne weitere Kenntnis, ob es zuvor evtl. mal eine Ehe bestand. Im Prinzip als Überbegriff für ledig, verwitwet, geschieden, wenn zwischen diesen Konzepten nicht weiter differenziert werden kann.

2021-05-24 12:22 UTC, closed without merging

2021-05-24 12:23 UTC, simoneOnFhir commented
Wollten wir nicht unverheiratet lassen und Never married mit ledig übersetzen?

2021-05-24 12:23 UTC, simoneOnFhir requested changes
Never married = ledig