Broken link fixes
hl7germany/basisprofil-de-r4 pull request #469
Opened 2022-09-14 18:12 UTC by ylboerner

2022-09-16 21:47 UTC, alexzautke requested changes

2022-09-16 21:47 UTC, alexzautke commented on ig/markdown/Ressourcen-Observation-VitalParameter.md
> +Diese Profile sind angelehnt an die Internationlen [VitalSign Profile](http://hl7.org/fhir/R4/observation-vitalsigns.html) enthalten jedoch technische Korrekturen (Verbessertes Slicing und korrigiert
"https" bitte

2022-09-16 21:47 UTC, alexzautke commented on ig/markdown/Terminologie-NomenklaturDerRessourcen.md
> +- CodeSystems, ValueSets und NamingSystems, die im Rahmen des Basis-Profils erstmals *als FHIR-Resourcen* publiziert werden, erhalten eine canonical URL aus der Domäne
Link zu https://www.hl7.org/fhir/references.html#canonical einfügen?

2022-09-20 00:19 UTC, ylboerner commented on ig/markdown/Ressourcen-Observation-VitalParameter.md
> +Diese Profile sind angelehnt an die Internationlen [VitalSign Profile](http://hl7.org/fhir/R4/observation-vitalsigns.html) enthalten jedoch technische Korrekturen (Verbessertes Slicing und korrigiert
Done, merci

2022-09-20 00:19 UTC, patrick-werner approved these changes

2022-09-20 00:21 UTC, ylboerner commented on ig/markdown/Terminologie-NomenklaturDerRessourcen.md
> +- CodeSystems, ValueSets und NamingSystems, die im Rahmen des Basis-Profils erstmals *als FHIR-Resourcen* publiziert werden, erhalten eine canonical URL aus der Domäne
Definitiv, done!

2022-09-20 00:22 UTC, alexzautke approved these changes

2022-09-20 00:36 UTC, merged