Fix version Deuev CodeSystems
hl7germany/basisprofil-de-r4 pull request #489
Opened 2022-10-29 18:56 UTC by alexzautke

2022-10-31 14:25 UTC, ylboerner requested changes

2022-10-31 14:25 UTC, ylboerner commented on resources/input/fsh/codesystems/DeuevAnlage8Laenderkennzeichen.fsh
> +* ^version = "2.56"
Müsste das hier Version `8` sein? 

https://www.gkv-datenaustausch.de/media/dokumente/arbeitgeber/deuev/rundschreiben_anlagen/03_Gem_RS_Anlage_8_Vers._8.00.pdf

2022-11-01 08:27 UTC, alexzautke commented on resources/input/fsh/codesystems/DeuevAnlage8Laenderkennzeichen.fsh
> +* ^version = "2.56"
Ich würde die Versionsnummer aus dem letzten korrekten Release nehmen...

2022-11-01 14:10 UTC, ylboerner commented on resources/input/fsh/codesystems/DeuevAnlage8Laenderkennzeichen.fsh
> +* ^version = "2.56"
D'accord 👍

2022-11-01 14:10 UTC, ylboerner approved these changes

2022-11-01 14:10 UTC, merged